image: alpine:3.7

.angular_cli: &angular_job_definition
  image: trion/ng-cli-karma:$NG_CLI_VERSION
  tags:
    - shared
  cache:
    paths:
      - node_modules/
  before_script:
    - npm set progress=false
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm install

.angular_e2e: &angular_e2e_job_definition
  image: trion/ng-cli-e2e:$NG_CLI_VERSION
  before_script:
      - npm set progress=false
      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
      - npm install

stages:
  - test
  - build

lint:
  <<: *angular_job_definition
  stage: test
  script:
    - npm run lint

unit_test_phantom:
  <<: *angular_job_definition
  stage: test
  artifacts:
      paths:
        - coverage/
  script:
    - ng test -cc -sr --browsers=PhantomJS

unit_test_chrome:
  <<: *angular_job_definition
  stage: test
  artifacts:
      paths:
        - coverage/
  script:
    - ng test -cc -sr --browsers=ChromeHeadlessNoSandbox

automation_test:
  <<: *angular_e2e_job_definition
  stage: test
  artifacts:
      when: always
      paths:
        - automation-test-report/
  script:
    - ng e2e

compile_angular:
  <<: *angular_job_definition
  stage: build
  script:
    - npm run build:ssr


